### ISSUE TITLE
runtime dependencies missing?

### ISSUE THREAD

**Issue by jsoo1** [nikstur/bombon#60]
Looks like the runtime inputs are expected to be json but are newline separated filepaths:

https://github.com/nikstur/bombon/blob/dd57f234f3bbe9fa732130fe56e83ccfc2961ce4/runtime-dependencies.nix#L9

And here they are expected to be json: https://github.com/nikstur/bombon/blob/dd57f234f3bbe9fa732130fe56e83ccfc2961ce4/transformer/src/cli.rs#L20

Edit: Maybe those two things are just misleading comments and `include-buildtime-dependencies` just excludes runtime dependencies? https://github.com/nikstur/bombon/blob/dd57f234f3bbe9fa732130fe56e83ccfc2961ce4/transformer/src/transform.rs#L29

Edit 2: Actually it seems like the runtime dependencies are just never used?

Edit 3: Do I simply not understand how this works?

**Comment by nikstur** [comment]
The comment ist definitely wrong here. I've noticed some unexpected behaviour. I'll look into it.

**Comment by jsoo1** [comment]
Thank you! Looks much closer to what I expected now!
